- hosts: localhost
  tasks:
  - name: install git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: clone petclinic
    git:
      repo: https://github.com/ifriedman/spring-petclinic.git
      dest: ~/petclinic
      clone: yes
  - name: clone ciscocd
    git:
      repo: https://github.com/ifriedman/ciscocd.git
      dest: ~/ciscocd
      clone: yes
  - name: download maven and unarchive
    unarchive:
      src: http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
      dest: ~/maven
      remote_src: True